### ISSUE TITLE
Admin user can be deleted

### ISSUE THREAD

**Issue by coolwidgets** [ikkez/fabulog#10]
I accidentally deleted admin user and now unable to log in admin panel. You should not allow to delete admin user.

**Comment by ikkez** [comment]
Well, on my live demo, it is not possible. You can edit this lines 
https://github.com/ikkez/fabulog/blob/master/app/controller/user.php#L49
https://github.com/ikkez/fabulog/blob/master/app/controller/user.php#L34
for your needs. But for future support, i guess we need a user roles / groups to be able to better control permissions. So maybe only admin users can delete users, and editors can only edit their own account or something like that.
