### ISSUE TITLE
Rewrite rule is redirecting www.mysite.com to mysite.com

### ISSUE THREAD

**Issue by zeon** [ikkez/fabulog#13]
Hi There,

Currently your rewrite rule will turn my url www.mysite.com to mysite.com could you please tell me how to disable this?

**Comment by ikkez** [comment]
Just remove these lines:
https://github.com/ikkez/fabulog/blob/master/.htaccess#L10-L13

**Comment by zeon** [comment]
I did but then I am unable to login from the backend, it spins for a while then the page stays at the login page.

**Comment by ikkez** [comment]
That's weird indeed. I had the same issue too here but only once. I cleared my tmp/ folder an removed my domain cookies and now the problem is gone and it works.

**Comment by zeon** [comment]
I did the same and it fixed it, thanks.
