### ISSUE TITLE
Dynamic meta info in header section

### ISSUE THREAD

**Issue by zeon** [ikkez/fabulog#14]
The title and description in the header area are currently all identical, how do I make it to load from the variable value I set in each controller? I've tried to set the variable in each controller but the layout.html always loads first than the other page.

**Comment by ikkez** [comment]
I do not understand. When you set the variable in the controller, the variable is available when the afterrender method will render the layout.html. so just place that variable in the head section and it should work.

**Comment by zeon** [comment]
Got it, thanks! Thanks for your help. I really love your work and have been
using it as the base skeleton to do so many projects.

2016-04-03 2:07 GMT+08:00 Christian Knuth <notifications@github.com>:
