### ISSUE TITLE
Demo is throwing error

### ISSUE THREAD

**Issue by leancode** [ikkez/fabulog#20]
http://ikkez.de/fabulog/
Internal Server Error
Invalid query: unbalanced brackets found
Then in a black box in red writing (almost unreadable)
[fabulog/vendor/bcosca/fatfree-core/base.php:2178] Base->error()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:2481] trigger_error()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:2250] DB\CortexQueryParser->_mongo_parse_logical_op()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:751] DB\CortexQueryParser->prepareFilter()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:609] DB\Cortex->filteredFind()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:1718] DB\Cortex->find()
[fabulog/vendor/ikkez/f3-cortex/lib/db/cortex.php:619] DB\Cortex->get()
[fabulog/app/controller/tag.php:39] DB\Cortex->find()
[fabulog/app/controller/post.php:47] Controller\Tag->tagCloud()
[fabulog/vendor/bcosca/fatfree-core/base.php:1791] call_user_func_array()
[fabulog/vendor/bcosca/fatfree-core/base.php:1612] Base->call()
[fabulog/index.php:70] Base->run()

**Comment by ikkez** [comment]
fixed by updating composer libs
