### ISSUE TITLE
trying the demo version with admin user at https://ikkez.de/fabulog/admin/post  Gives Internal server Error

### ISSUE THREAD

**Issue by eliargon** [ikkez/fabulog#23]

**Comment by NetLancer** [comment]
Yeah, i had the same problem coupla months ago (xamp with php7.2 on linux)..
After few attempts to cope with that - no success, just left :(

**Comment by ikkez** [comment]
well I had some ownership/access issues with the files after moving to a new server, so the templates were not able to update.. issue solved now.
