### ISSUE TITLE
echo in both controller->afterroute and view->render

### ISSUE THREAD

**Issue by doonge** [ikkez/fabulog#5]
Hello,

it's not really a problem as everything works wonder, but I wonder why there is an echo in both the controllers->afterroute (which invokes view->render) and the views->render themselves (which return nothing, so the echo in the controller doesn't look useful).

The code does this:

in Controller->afterroute:
echo $this->response->render();

in View->render()
echo \Template::instance()->render($this->template);
(returns nothing)

Is this a safeguard for custom Views?
Best whishes.

**Comment by ikkez** [comment]
hi. yeah i guess one of it is superfluous. I guess there should be a return instead of echo in the View.
I'll fix this. thanks ;)

**Comment by ikkez** [comment]
fixed
